### ISSUE TITLE
Fix z-index on image hover on product page

### ISSUE THREAD

**Issue by jayhawk24** [jayhawk24/E-store#9]
![image](https://user-images.githubusercontent.com/38766415/194771286-f8baef5b-4830-4fa6-940d-af878b67b992.png)

**Comment by jsvigneshkanna** [comment]
Assign me this issue, will work on this

**Comment by jsvigneshkanna** [comment]
@jayhawk24 , please share env file, the code isnt working in my local

**Comment by jayhawk24** [comment]
CLOUDINARY_API_KEY=54523452345534523
CLOUDINARY_API_SECRET=rwetewrtwe425345234
CLOUDINARY_CLOUD_NAME=d23452345
DEPLOYED_URL=https://estore24.herokuapp.com
GOOGLE_CLIENTID=kjlrngk23-ergrgdrgnkjn213.apps.googleusercontent.com
GOOGLE_CLIENTSECRET=23453452345234
MERCHANT_KEY=jafskelfas
MERCHANT_SALT=kjasenfkla
MONGODB_URI=mongodb+srv://dbUser:szyMEnKw8K8YfQx@cluster0.cvynx.mongodb.net/ecommerce?retryWrites=true&w=majority
SESSION_SECRET=zmk^{R_R3HD:D2v[88w}

**Comment by jsvigneshkanna** [comment]
Hi @jayhawk24 ,

Raised the PR #12 
Please check the code and let me know if any changes needed
